language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - php vendor/bin/php-coveralls
  